version: '3.1'
name: '${PROJECT_NAME}'
services:
  db:
    container_name: '${PROJECT_NAME}-db'
    mem_limit: 2048m
    image: mariadb:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./:/app
      - ./sh/:/sh
      - ./backups/:/backups
      - ./docker/data/db/:/var/lib/mysql
      - ./docker/ini/db/:/docker-entrypoint-initdb.d
    # labels:
    #   - "traefik.http.routers.${PROJECT_NAME}_wordpress.rule=Host(`db.${PROJECT_BASE_URL}`)"

  # phpmyadmin:
  #   container_name: '${PROJECT_NAME}-phpmyadmin'
  #   depends_on:
  #     - db
  #   image: phpmyadmin
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
  #   ports:
  #     - 8081:80
  #   # labels:
  #   #   - "traefik.http.routers.${PROJECT_NAME}_phpmyadmin.rule=Host(`pma.${PROJECT_BASE_URL}`)"

  wordpress:
    container_name: '${PROJECT_NAME}-wordpress'
    depends_on:
      - db
    image: wordpress:6.4.2-apache
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_DEBUG: '${WORDPRESS_DEBUG}'
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./sh/:/sh
      - ../:/var/www/html/wp-content/themes/lotsof/vendor/lotsof
      - ./backups/:/backups
      - ./docker/config:/etc/nginx/conf.d
      - ./wordpress/:/var/www/html
      - ./docker/ini/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    # labels:
    #   - 'traefik.http.routers.${PROJECT_NAME}_wordpress.rule=Host(`${PROJECT_BASE_URL}`)'

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   container_name: '${PROJECT_NAME}-mailhog'
  #   restart: unless-stopped
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
  #   # labels:
  #   #   - 'traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)'

  # traefik:
  #   image: traefik:v2.0
  #   container_name: '${PROJECT_NAME}-traefik'
  #   command: --api.insecure=true --providers.docker
  #   env_file: .env
  #   ports:
  #     - '${PROJECT_PUBLIC_PORT}:80'
  #     - '8080:8080'
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
